### ISSUE TITLE
I can't swap spells.

### ISSUE THREAD

**Issue by ccuthbert001** [Safrodev/Archon#10]
I had a wand that had propel on on it, I found a tome for gust, used it and swapped to the spell, now I cant swap back to propel. I tried to use another propel tome but it said I already learned the spell. Now I'm stuck with gust even though I'd rather have propel. This is on version 1.18.2 and on archon version 0.3.1 on server and client.

**Comment by Safrodev** [comment]
This is a known issue likely due to syncing mistakes. I will work on a fix soon.

**Comment by Safrodev** [comment]
This _should_ be fixed in v0.3.2, please lmk if it is not

**Comment by ccuthbert001** [comment]
> This _should_ be fixed in v0.3.2, please lmk if it is not

Yep, it's fixed now! Thanks!
