### ISSUE TITLE
Hitting Summoned Skeletons Cases A Crash

### ISSUE THREAD

**Issue by SynnBunn** [Safrodev/Archon#11]
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 7/24/22, 7:15 AM
Description: Ticking entity

java.lang.ClassCastException: class safro.archon.entity.SkeltEntity cannot be cast to class net.minecraft.class_5354 (safro.archon.entity.SkeltEntity and net.minecraft.class_5354 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @4520ebad)
	at net.minecraft.entity.ai.goal.UniversalAngerGoal.start(UniversalAngerGoal:51)
	at net.minecraft.entity.ai.goal.PrioritizedGoal.start(PrioritizedGoal:41)
	at net.minecraft.entity.ai.goal.GoalSelector.tick(GoalSelector:106)
	at net.minecraft.entity.mob.MobEntity.tickNewAi(MobEntity:738)
	at net.minecraft.entity.LivingEntity.tickMovement(LivingEntity:2609)
	at net.minecraft.entity.mob.MobEntity.tickMovement(MobEntity:546)
	at net.minecraft.entity.passive.PassiveEntity.tickMovement(PassiveEntity:127)
	at net.minecraft.entity.passive.AnimalEntity.tickMovement(AnimalEntity:58)
	at net.minecraft.entity.LivingEntity.tick(LivingEntity:2354)
	at net.minecraft.entity.mob.MobEntity.tick(MobEntity:346)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:702)
	at net.minecraft.world.World.tickEntity(World:485)
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld:363)
	at net.minecraft.world.EntityList.forEach(EntityList:54)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:331)
	at net.minecraft.server.MinecraftServer.redirect$bla000$fixUpdateSuppressionCrashTick(MinecraftServer:6290)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:907)
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:322)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:851)
	at net.minecraft.server.MinecraftServer.handler$bdm000$modifiedRunLoop(MinecraftServer:5396)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273)
	at java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_5398.method_6269(class_5398.java:51)
	at net.minecraft.class_4135.method_6269(class_4135.java:41)
	at net.minecraft.class_1355.method_6275(class_1355.java:106)
	at net.minecraft.class_1308.method_6023(class_1308.java:738)
	at net.minecraft.class_1309.method_6007(class_1309.java:2609)
	at net.minecraft.class_1308.method_6007(class_1308.java:546)
	at net.minecraft.class_1296.method_6007(class_1296.java:127)
	at net.minecraft.class_1429.method_6007(class_1429.java:58)
	at net.minecraft.class_1309.method_5773(class_1309.java:2354)
	at net.minecraft.class_1308.method_5773(class_1308.java:346)
	at net.minecraft.class_3218.method_18762(class_3218.java:702)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)
	at net.minecraft.server.MinecraftServer.redirect$bla000$fixUpdateSuppressionCrashTick(MinecraftServer.java:6290)

-- Entity being ticked --
Details:
	Entity Type: archon:skelt (safro.archon.entity.SkeltEntity)
	Entity ID: 74
	Entity Name: entity.archon.skelt
	Entity's Exact location: -529.74, 88.36, 154.61
	Entity's Block location: World: (-530,88,154), Section: (at 14,8,10 in -34,5,9; chunk contains blocks -544,-64,144 to -529,319,159), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,-64,0 to -513,319,511)
	Entity's Momentum: 0.11, 0.28, -0.19
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {AbsorptionAmount:0.0f,Age:0,Air:300s,ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],ArmorItems:[{},{},{},{}],Attributes:[{Base:0.08d,Name:"porting_lib:entity_gravity"},{Base:0.25d,Name:"minecraft:generic.movement_speed"},{Base:0.0d,Name:"stepheightentityattribute:stepheight"}],BalmData:{},Brain:{memories:{}},CanPickUpLoot:0b,DeathTime:0s,FallDistance:0.0f,FallFlying:0b,Fire:-1s,ForcedAge:0,HandDropChances:[0.085f,0.085f],HandItems:[{},{}],Health:14.5f,HurtByTimestamp:837,HurtTime:8s,InLove:0,Invulnerable:0b,LeftHanded:0b,Motion:[0.11198188956520745d,0.2751840104494096d,-0.18750634365685329d],OnGround:0b,Owner:[I;-2126790789,717639486,-1127952347,-1798657461],PersistenceRequired:0b,PortalCooldown:0,Pos:[-529.7385883864349d,88.36080000519752d,154.60652031598113d],Rotation:[45.328583f,0.0f],Sitting:0b,UUID:[I;1000652951,-1148436227,-2103329186,1546458154],cardinal_components:{"apoli:powers":{Powers:[]},"eldritch_mobs:eldritch_modifiers":{eldritch:0b,elite:0b,rank:0b,saved_mods:{},ultra:0b},"the_aether:condition_manager":{"the_aether:venom":{chronic:0.0f,temporary:0.0f}},"twilightforest:cap_shield":{permshields:0,tempshields:0}},checkedIfInLampChunk:0b,cpaCooldown:0,cpadidTP:0b}
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)
	at net.minecraft.server.MinecraftServer.redirect$bla000$fixUpdateSuppressionCrashTick(MinecraftServer.java:6290)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.class_3176.method_3813(class_3176.java:322)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.handler$bdm000$modifiedRunLoop(MinecraftServer.java:5396)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 2 total; [class_3222['LOGICHACK'/233, l='ServerLevel[world]', x=-533.33, y=90.00, z=156.07], class_3222['DeathGoddessRii'/292, l='ServerLevel[world]', x=-530.57, y=89.00, z=156.00]]
	Chunk stats: 3171
	Level dimension: minecraft:overworld
	Level spawn location: World: (-464,65,128), Section: (at 0,1,0 in -29,4,8; chunk contains blocks -464,-64,128 to -449,319,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 423645 game time, 361656 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 9408 (now: true), thunder time: 116388 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.class_3176.method_3813(class_3176.java:322)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.handler$bdm000$modifiedRunLoop(MinecraftServer.java:5396)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 5.15.0-25-generic
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1000230240 bytes (953 MiB) / 2884538368 bytes (2750 MiB) up to 8109031424 bytes (7733 MiB)
	CPUs: 1
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 64854.57
	Virtual memory used (MB): 20730.36
	Swap memory total (MB): 32735.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms128M -Xmx8000M
	Fabric Mods: 
		actioninventory: Action Inventory Mod 3.2.0
		advancednetherite: Advanced Netherite 1.5.1-1.18.2
		airhop: Air Hop 3.2.0
		architectury: Architectury 4.5.76
		archon: Archon 0.3.1
			omega-config: OmegaConfig 1.2.3-1.18.1
		armor-stand-editor: Armor Stand Editor 1.3.2+1.18.2
		balm-fabric: Balm 3.1.0+0
		bclib: BCLib 1.4.7
		betterend: Better End 1.1.1
		betternether: Better Nether 6.1.2
		bettervillage: Better Village 1.0.2
		bitsandchisels: BitsAndChisels 2.6.13
		blockus: Blockus 2.4.7+1.18.2
			terraform-wood-api-v1: Terraform Wood API (v1) 3.0.0
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.7-1.18.2
			maelstrom_library: Maelstrom Library 1.2.4-1.18.2
			multipart_entities: MultipartEntities 1.1.5-1.18.2
		botania: Botania 1.18.2-434-FABRIC
			fiber: fiber 0.23.0-2
			reach-entity-attributes: Reach Entity Attributes 2.1.1
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		cardinal-components: Cardinal Components API 4.2.0
			cardinal-components-base: Cardinal Components API (base) 4.2.0
			cardinal-components-block: Cardinal Components API (blocks) 4.2.0
			cardinal-components-chunk: Cardinal Components API (chunks) 4.2.0
			cardinal-components-entity: Cardinal Components API (entities) 4.2.0
			cardinal-components-item: Cardinal Components API (items) 4.2.0
			cardinal-components-level: Cardinal Components API (world saves) 4.2.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 4.2.0
			cardinal-components-world: Cardinal Components API (worlds) 4.2.0
		carpet: Carpet Mod 1.4.69
		chunky: Chunky 1.2.164
		cloth-config: Cloth Config v6 6.2.62
			cloth-basic-math: cloth-basic-math 0.6.1
		collective-fabric: Collective (Fabric) 4.27
		cosmetic-armor: Cosmetic Armor 1.3.1
		creatures_from_the_warmths: Creatures From The Warmths 2.1.0+1.18.2
		creeperoverhaul: Creeper Overhaul 1.3.1
		cursery: Cursery Mod 1.18.2-3.0
		cyanide: Cyanide (Fabric) 2.1.1
		disguiselib: Disguise Library 1.2.2
		earthbounds: Earthbounds 1.18.2-1.1.3
		ecologics: Ecologics 1.7.3
		eldritch_mobs: Eldritch Mobs 1.11.0
		endgoblintraders: End Goblin Traders 1.5 (Re-upload)
		expandedstorage: Expanded Storage 7.3.12
		extraorigins: Extra Origins 1.18-11
		fabric: Fabric API 0.57.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.22+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.0+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.18+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.1+6c4e5d0960
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.22+e6b169eb60
			fabric-networking-v0: Fabric Networking (v0) 0.3.9+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.9+0d9ab37260
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.1+1f6558e860
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.7.4+kotlin.1.6.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.21
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		fabricloader: Fabric Loader 0.14.8
		fantasy-origins: FantasyOrigins 1.0.3
		farmersdelight: Farmer's Delight 1.18.2-0.2.1
		fdlink: Fabric <-> Discord Link 0.10.8
			fdlink_1_12_2: Fabric <-> Discord Link 0.10.8
			fdlink_1_15_2: Fabric <-> Discord Link 0.10.8
			fdlink_1_16: Fabric <-> Discord Link 0.10.8
			fdlink_1_6_4: Fabric <-> Discord Link 0.10.8
			fdlink_1_7_10: Fabric <-> Discord Link 0.10.8
			fdlink_1_8_9: Fabric <-> Discord Link 0.10.8
			fdlink_api: Fabric <-> Discord Link API 0.1.2
			fdlink_common: Fabric <-> Discord Link 0.10.8
				club_minnced_discord-webhooks: discord-webhooks 0.7.2
				com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.10.1
				com_fasterxml_jackson_core_jackson-core: jackson-core 2.10.1
				com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.10.1
				com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
				com_squareup_okhttp3_okhttp: okhttp 3.14.9
				com_squareup_okio_okio: okio 1.17.2
				com_vdurmont_emoji-java: emoji-java 5.1.1
				net_dv8tion_jda: JDA 4.4.0_352
				net_sf_trove4j_trove4j: trove4j 3.0.3
				org_apache_commons_commons-collections4: commons-collections4 4.1
				org_json_json: json 20210307
				org_slf4j_slf4j-api: slf4j-api 1.8.0-beta4
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		firstjoinmessage-fabric: First Join Message (Fabric) 1.3
		fishofthieves: Fish of Thieves 1.0.7
		flan: Flan 1.18.2-1.7.10
		forgeconfigapiport: Forge Config API Port 3.2.0
		friendsandfoes: Friends&Foes 1.4.5
			mm: Manningham Mills 2.3
		geckolib3: Geckolib 3.0.50
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		goblintraders: Goblin Traders 1.5.1
		guild: Guild 0.4.0
		icarus: Icarus 1.11
		impersonate: Impersonate 2.5.0
		invview: InvView 1.4.8-1.18+
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.1.9
			com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		ledger: Ledger 1.2.4
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		levelz: LevelZ 1.3.3
		libraryferret: Library Ferret 2.0.0
		lithium: Lithium 0.7.10
		lootgoblins: Lootgoblins 1.0.8
		lootr: Lootr 0.3.21.58
		luckperms: LuckPerms 5.3.86
		mcda: MC Dungeons Armors 2.0.7
		mcdar: MC Dungeons Artifacts 1.4.8
		midnightlib: MidnightLib 0.4.4
		minecraft: Minecraft 1.18.2
		mob_catcher: Mob Catcher 1.1.27
		modid: Creatures Of The Snow 2.1.0+1.18.2
		mythicmounts: Mythic Mounts 1.18.2-7.0
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.3.0
		notenoughcrashes: Not Enough Crashes 4.1.6+1.18.2
		numismatic-overhaul: Numismatic Overhaul 0.2.2+1.18
			stacc: Stacc 1.3.0
		origins: Origins 1.4.1
			apoli: Apoli 2.3.3
				additionalentityattributes: Additionalentityattributes 1.0.0+1.18.2
				calio: Calio 1.5.1
				playerabilitylib: Pal 1.5.0
		ottercraft: Ottercraft 1.1.12
			org_antlr_antlr4-runtime: antlr4-runtime 4.7.2
			org_tomlj_tomlj: tomlj 1.0.0
		owo: oωo 0.7.2-no-cme+1.18
		patchouli: Patchouli 1.18.2-71.1-FABRIC
		pehkui: Pehkui 3.3.3+1.14.4-1.19.1
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		phosphor: Phosphor 0.8.1
		pickupnotifier: Pick Up Notifier 3.2.0
		potiontotems: potiontotems 1.0.0
		probablychests: Probably Chests 0.4.3.1
			libgui: LibGui 5.3.2+1.18.2
				jankson: Jankson 4.0.0+j1.2.0
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		progressivebosses: Progressive Bosses 1.0.0
			completeconfig: CompleteConfig 1.4.1
		puzzleslib: Puzzles Lib 3.3.5
		repurposed_structures: Repurposed Structures 4.1.14+1.18.2
		rocks: This Rocks! 1.6.0
		seedfix: Seed Fix 1.0.1
		skylorlib: SkyLib 1.3.35
		sound_physics_remastered: Sound Physics Remastered 1.18.2-1.0.6
		starterkit-fabric: Starter Kit (Fabric) 3.1
		styledplayerlist: Styled Player List 2.1.3+1.18
			player-data-api: Player Data API 0.1.0+1.18
		subterrestrial: Subterrestrial 1.0.2
		t_and_t: Towns and Towers - Structure Add-on 1.6
		tatercart: TaterCart 1.0.0-pre.4+1.18.2
			hologram-api: Hologram API 0.2.1+1.18-pre5
			placeholder-api: Placeholder API 1.1.3+1.17.1
			polymer: Polymer (Core) 0.2.0-pre.6+1.18.2
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
				polymer-legacy: Polymer (Compatibility) 0.1.9+0.2.0-pre.6+1.18.2
			server_translations_api: Server Translations API 1.4.12+1.18.2
			sgui: sgui 1.0.2+1.18.2
		taterzens: Taterzens 1.9.6
			config2brigadier: Config to Brigadier 1.1.1
		terrablender: TerraBlender 1.1.0.102
			com_electronwill_night-config_core: core 3.6.4
			com_electronwill_night-config_toml: toml 3.6.4
		the_aether: Paradise Lost 1.6.9+1.18.2
			crowdin-translate: CrowdinTranslate 1.4+1.18.2
			customportalapi: Custom Portal Api 0.0.1-beta50-1.18
			gud_recipe_confidence: Recipe Confidence 1.0.2
			incubus_core: Incubus Core 1.6.6+1.18.2
			moretags: More Tags 3.0.4
		thonkutil: ThonkUtil 2.14.1+1.18
			thonkutil-base: ThonkUtil Base 1.12.2+23c1dc2c60
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.3.2+9e23427060
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.0.14+9b80223760
			thonkutil-legacy: ThonkUtil Legacy 1.0.20+9b80223760
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.0.12+9b80223760
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.4.1+9b80223760
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.1.20+9b80223760
		timeoutout: TimeOut Out 1.0.1+1.18
		totw_additions: Towers of the Wild: Additions 1.2.1
		transferpet: Pet Transfer 0.0.5
		trashslot: TrashSlot 11.0.2
		travelersbackpack: Traveler's Backpack 1.18.2-7.1.2
		trinkets: Trinkets 3.3.1
		trulytreasures: Truly Treasures fabric-1.18.1-2.0.1
		twilightforest: The Twilight Forest 4.1.251
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			forge_tags: Forge Tags 2.1
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			porting_lib: Porting Lib 1.1.342-beta+1.18.2-dev.dd61cdc
				com_github_llamalad7_mixinextras: MixinExtras 0.0.10
				serialization_hooks: Serialization Hooks 0.2.0+1.18.f5d4aa6
		untitledduckmod: Untitled Duck Mod 0.4.1
		vanilla_degus: Vanilla Degus 1.3.0
		villager-hats: Villager Hats 1.4.0
		waystones: Waystones 2.5.5+mc1.18.2
		wildlife: Wildlife 1.18.2-2.0
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.8
	Server Running: true
	Player Count: 2 / 20; [class_3222['LOGICHACK'/233, l='ServerLevel[world]', x=-533.33, y=90.00, z=156.07], class_3222['DeathGoddessRii'/292, l='ServerLevel[world]', x=-530.57, y=89.00, z=156.00]]
	Data Packs: vanilla, file/Artifacts_1.zip (incompatible), file/CS Dragon Overhaul v1.0.2, file/Towers_Of_The_Wild_Reworked_v3.0.0_Fabric_Waystones.zip, file/havenorigins.zip (incompatible), file/levelz and advanced netherite datapack 1.18.1 (incompatible), file/levelz and better nether datapack 1.18.1 (incompatible), file/levelz and betterend datapack 1.18.1 (incompatible), file/levelz and botania datapack 1.18.1 (incompatible), file/levelz and mcda datapack 1.18.1 (incompatible), file/levelz and minecraft datapack 1.18.1 (incompatible), file/levelz_and_mcda_datapack_1.18.1.zip (incompatible), Fabric Mods
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
	Suspected Mods: None

**Comment by Safrodev** [comment]
Fixed in v0.3.2
