### ISSUE TITLE
Bookshelfs dont enhance the Enchanting Table

### ISSUE THREAD

**Issue by xanthian** [Safrodev/Archon#12]
As title.

Put appropriate amount of bookshelves around the enchanting table, no level 30 enchant available.
Repeat process with vanilla bookshelf, level 30 enchant shown

**Comment by Safrodev** [comment]
Archon doesn’t affect the enchanting system in any way, did you mean the magical bookshelves?

**Comment by xanthian** [comment]
yup :)

**Comment by Safrodev** [comment]
Ah okay. The magical bookshelves aren’t intended to work with enchantment tables but I can provide supper for that if you’d like.

**Comment by xanthian** [comment]
if its not intended then thats cool, feel free to close :)

**Comment by Safrodev** [comment]
It's all good, I've added the feature in v0.3.2
