### ISSUE TITLE
Add command to list learned spells?

### ISSUE THREAD

**Issue by Malvisk** [Safrodev/Archon#16]
I've learned three spells, don't know what element they are tied to.  I learned them before I knew how to make the guide for thee mod. It would be nice if the grimoire would provide info on spells. It would be nice if there was a command to list all the spells you've learned.

**Comment by Safrodev** [comment]
The grimoire does provide info on all of the spells and there is a command to list all of the spells. Operators can use /spell <player> to get the spells of a player. The grimoire has an entire spell category which describes all spells, wands, and tomes.
