### ISSUE TITLE
[Feature Suggestion] Add cooldowns to weapons, staffs, wands, and other tools that uses mana

### ISSUE THREAD

**Issue by kingkuys2123** [Safrodev/Archon#17]
Minecraft 1.19.2
Fabric Loader 0.14.10
Fabric Api 0.64.0

Archon 0.4.1

- Add cooldowns to weapons, staffs, wands, and items that uses mana 
>> I have received a number of complaints from my private server that players have used this mod's weapons and tools abusively, like, for example, the heat ranger bow. It's too OP; players can spam right-clicking, and it's also too destructive, and griefers loved this, hahaha, so yeah that's why I'm suggesting implementing cooldowns to these weapons and also maybe a game rule would also disable the destructive features of the bow? The players also say that the lightning staff is too powerful because we can also spam right-clicking it, resulting in instant death. Also, for cleavers, I would suggest adding a cooldown to this weapon as well, like 3-5 seconds, and so for the other weapons that use mana.

**Comment by Safrodev** [comment]
Adding cooldowns on weapons and wands would change the balance of the mod drastically. It can be prevented on your end however by installing a claim system possibly. You can also turn off mob griefing to prevent the heat ranger to stop griefing.
