### ISSUE TITLE
Grimoir doesn't display text

### ISSUE THREAD

**Issue by thyslayer221** [Safrodev/Archon#18]
![issue](https://user-images.githubusercontent.com/46456975/201911746-c3e0866f-616a-41f8-9ac9-bb22cbc42c0e.PNG)
The grimoir dosen't seem to register the font for descriptors. No idea what's causing it.

**Comment by Safrodev** [comment]
This isn’t a problem on Archon’s end I believe. Patchouli uses a custom font for books and some mod is conflicting with the loading of the font. If you have a resource loader mod that could be conflicting with it.

**Comment by thyslayer221** [comment]
Issue resolved itself. Thanks for the help!
