### ISSUE TITLE
[feature request] EMI plugin

### ISSUE THREAD

**Issue by fzzyhmstrs** [Safrodev/Archon#19]
Hi! It would be really cool if you could add a plugin for EMI recipe viewing compatibility. 

https://github.com/emilyploszaj/emi/wiki/Getting-Started-Guide

I would be willing to help with it if you don't have the time, energy etc.

**Comment by Safrodev** [comment]
I can try to yes, but I don't know how long it will take as I am adding some new content as well. If you'd like to make a PR that would be much appreciated!

**Comment by fzzyhmstrs** [comment]
Awesome! I could look into working on a PR at some point soon. If you find some time and beat me to it, all's well :)

**Comment by fzzyhmstrs** [comment]
opened a PR for this :).

**Comment by Safrodev** [comment]
Sorry it took so very long but you can now officially use EMI
