### ISSUE TITLE
[Bug?] Abilities from scrolls (Capacity/Accelerate, etc) disappear upon death and possibly after using the ender portal in The End

### ISSUE THREAD

**Issue by varencilator** [Safrodev/Archon#20]
After getting a Scroll ability, if you die or travel back from the End:
It seems like the game thinks you still have the Scroll attributes associated with the player but the effects are not given.

You need to use the Removal scroll to reset having a scroll applied before reapplying a new scroll.

**Comment by Safrodev** [comment]
This is a known issue but unfortunately I’ve been having trouble trying to fix it. I’m not sure how long it may take, sorry about this.

**Comment by Safrodev** [comment]
Fixed as of v0.5.0
