### ISSUE TITLE
Feature Request - Integration with Spell Power/Spell Engine

### ISSUE THREAD

**Issue by ghost** [Safrodev/Archon#25]
I mentioned this on your discord, but figured I’d write this for easier tracking and a better description. 

https://www.curseforge.com/minecraft/mc-mods/spell-power

Integration with Spell Power would be simplest and least intrusive, simply make your spell damage formulas scale using Spell Power Attributes - SpellPower.getSpellPower(Fire,player), getCriticalChance/Damage if appropriate etc. (these classes also factor in enchantments as opposed to the spell_power entity attributes). Spell power has schools appropriate for most of your spells already, however there’s no “water spell power” attribute, only ice or healing. 

Spell Engine might be a little trickier - this might look something like registering your wands with its enchantments, making spells cost runes instead of mana, and shifting spell acquisition from the current book system to the Spell Engine’s Binding Table. I can imagine plenty of reasons why you wouldn’t want to do this, but that’s what would be most consistent. 

At the very least, I would love to see spell power integration. I’m a big fan of archon as it is and it would be great to have it integrated into a bigger fabric-side magic ecosystem, especially for modpacks.

**Comment by Safrodev** [comment]
Spell Power compat is in the works, I appreciate the detailed suggestion.

**Comment by ghost** [comment]
Awesome.

**Comment by Safrodev** [comment]
Available as of v0.5.0
