### ISSUE TITLE
Necromancy Bug

### ISSUE THREAD

**Issue by Retzl42** [Safrodev/Archon#28]
I have been playing for days killing with the soul scythe and have not gotten a single soul. I have tried with an enchanted one (looting 3) and with a base one. What can i do to fix this?

I am playing on the modpack AQM2

**Comment by Safrodev** [comment]
What kind of mobs have you tried killing? You might be killing things that don’t drop souls.

**Comment by Retzl42** [comment]
I have tried skeletons, zombies, anything that moves really.

**Comment by Safrodev** [comment]
Ah yeah, skeletons and zombies don’t work since they are already “dead”. I recommend checking out these tags: https://github.com/Safrodev/Archon/tree/main/src/main/resources/data/archon/tags/entity_types

**Comment by Retzl42** [comment]
Now that you say the need to be alive, I feel dumb, but I should have figured that out xD
Just a question about the lists that you sent. The second half of the creatures and the player list show a "false" in the code, does that mean those aren't included or is that just code language?

Thank you for taking the time to answer me :)

**Comment by Safrodev** [comment]
Oh that’s just part of the code. All the mobs on the list are included and will drop souls. No problem!
