### ISSUE TITLE
Grimoire with other mods

### ISSUE THREAD

**Issue by Nova0506** [Safrodev/Archon#29]
So I have Archon but I also have amythest imbument. I cannot craft the grimoire with the recipe because the other mod makes it craft the glistening tome/aka the help book for the other mod. How do I fix?

**Comment by Safrodev** [comment]
The only way to fix this on your end is to make a data pack or use a KubeJs type mod to make a new recipe.

**Comment by Retzl42** [comment]
When you have everything in its place for the correct recipe that you want, look at the "completed" item and you may see a swirl of two arrows in a circle (i called it a switch out symbol)

**Comment by Safrodev** [comment]
Ah yeah, you can use a mod that cycles recipes too
