### ISSUE TITLE
Super Experience Pouch shows 200 capacity

### ISSUE THREAD

**Issue by Sewef** [Safrodev/Archon#31]
![image](https://user-images.githubusercontent.com/27089398/229347521-8a327fe4-8f36-4d0b-ba66-87631bc384ac.png)

Version 0.4.1 / Fabric 0.14.18 / MC 1.19.2

**Comment by Safrodev** [comment]
Just checked it and you're right. Not sure why it does that but it will be fixed in an upcoming release.

**Comment by Safrodev** [comment]
Fixed in the latest version, I forgot to mention
