### ISSUE TITLE
Config not applying changes properly

### ISSUE THREAD

**Issue by Landon-9999** [Safrodev/Archon#33]
This section in the config does nothing on the latest version. Mana still displays when setting the value to true.
 
 There might be other sections in the config that don't work but the section below is all that I've tested.
 
 //Determines whether mana should only display if you have a mana item in your hand.
  //Client-Sided, Accepts "true" or "false"
  //Default: false (always shows mana)
  "displayManaWithItem": true,
  
Using archon-0.5.0.jar

**Comment by Safrodev** [comment]
That’s strange, I will look into it. I haven’t really checked the config for a while so something may have broken.

**Comment by Safrodev** [comment]
I know it's been a while since this issue was first posted but I did some testing and found that the config options work fine for me. Do you happen to be playing on a server?

**Comment by Landon-9999** [comment]
Yeah dedicated server. So maybe server config was overriding client config? Even for GUI option I guess? But haven't tested the theory and don't have the server up anymore because I've moved on from the modpack for now.

**Comment by Safrodev** [comment]
No worries, I just needed to know so I could test it myself. I believe the client-only options are still syncing with the server.
