### ISSUE TITLE
Infernal Coat Implosion Crash

### ISSUE THREAD

**Issue by shane1595042264** [Safrodev/Archon#39]
Version: 1.20.1 inigo crash fix

Steps to replicate: Try to use the ability of Infernal coat implosion.
![image](https://github.com/Safrodev/Archon/assets/61711097/561700d0-fe7e-41ca-8841-e9a5035112f2)

Modpack: Prominence 2 Fabric 1.4 hf
Video For demonstration:
https://www.youtube.com/watch?v=Hk1fNcID3CA

Log:
[latest.log](https://github.com/Safrodev/Archon/files/13224496/latest.log)

**Comment by Safrodev** [comment]
Are you on the latest version of Archon? (0.5.6)

**Comment by shane1595042264** [comment]
> Are you on the latest version of Archon? (0.5.6)

Yes. It's also in single-player, not on multiplayer. All you need to do to replicate is to use the coat's ability in singleplayer

**Comment by Safrodev** [comment]
The crash wasn't happening on my end when testing, but I think it's fixed now. Let me know if it still breaks.
