### ISSUE TITLE
Class inheritance error

### ISSUE THREAD

**Issue by Sunconure11** [Safrodev/Archon#4]
https://gist.github.com/Sunconure11/af07120444d6cc4ccb8f0c336ee0b5ea

**Comment by Safrodev** [comment]
I'm not sure why this is occuring at all. Archon does not mess with sealed classes or the EnchantmentTarget class. I will have to look into it.

**Comment by Sunconure11** [comment]
https://github.com/LordDeatHunter/Alloy-Forgery/issues/45

This may be connected.

**Comment by Sunconure11** [comment]
I found the culprit. More Bundles.

**Comment by Safrodev** [comment]
Ah, glad to see you found the culprit.
