### ISSUE TITLE
Earth Wand + Crush spell causes a crash

### ISSUE THREAD

**Issue by WavisDavis628** [Safrodev/Archon#42]
Maybe something to do with Archon? I get the same error with combustion charges.

[crash-2023-11-24_21.21.30-client.txt](https://github.com/Safrodev/Archon/files/13462949/crash-2023-11-24_21.21.30-client.txt)
](url)

**Comment by Safrodev** [comment]
The crash wasn't happening on my end when testing, but I think it's fixed now. Let me know if it still breaks.
