### ISSUE TITLE
Archon spells and items causing crashes when used in multiplayer

### ISSUE THREAD

**Issue by StipulateOlive1** [Safrodev/Archon#43]
I have been playing with this mod with a friend and as I've been trying to use the block altering items it causes client side crashes. I have logs for both and will send those in soon.
[crash-2023-11-30_01.38.46-client.txt](https://github.com/Safrodev/Archon/files/13509953/crash-2023-11-30_01.38.46-client.txt)

**Comment by Safrodev** [comment]
I see the problem, it has to do with my attempt at fixing another bug. It’s hard for me to catch these bugs because they don’t happen in dev for some reason.

**Comment by Safrodev** [comment]
Oh wait, you were not on the latest version of Archon. Please update to v0.5.7
