### ISSUE TITLE
Inigo still crashes

### ISSUE THREAD

**Issue by iShadowMonarch** [Safrodev/Archon#47]
Hello, I just wanted to let you know Inigo still crashes servers, same problem with missing particle. I've updated to the latest version and he still crashes my world.

**Comment by Safrodev** [comment]
Yikes not again... Do you happen to have logs so I can look into it? The new Inigo laser uses a different method of rendering the particles so it shouldn't be the same error.

**Comment by iShadowMonarch** [comment]
I play single player so I don't know how to pull up the logs for my world.
Basically, it says "Internal Exception: net.minecraft.class_148: Exception while adding particle".
You can spawn him in creative with the pedestal and you can work around him just fine, but as soon as you turn into survival mode he crashes my world.
