### ISSUE TITLE
Inigo killed on spawn

### ISSUE THREAD

**Issue by Mithenness** [Safrodev/Archon#48]
Hello! So when I summon Inigo he’ll spawn in and I’ll get a system message from “Neruina” that’s goes like this ‘Caught ticking entity [Inigo] at position [(xzy)]. It has been killed.” And he gets struck by lightning and dies! I can’t find any similar issues- please help

**Comment by gamerpotion** [comment]
hi, just checking if the inigo boss ticking entity server crash issue is still being looked into?

**Comment by Safrodev** [comment]
It is still being looked into and I have not yet found a fix. I am planning on changing the boss as a workaround.

**Comment by gamerpotion** [comment]
Thanks for the update. Sounds good.  If the workaround does not cause that issue, I can look to re-add it back into darkrpg. 
Will await an update.

**Comment by Safrodev** [comment]
Does anyone happen to have a log of the issue? I cannot replicate the crash myself no matter what I try, the boss works fine for me. Without a log of what's happening I can't find the source of the issue.

**Comment by gamerpotion** [comment]
> Does anyone happen to have a log of the issue? I cannot replicate the crash myself no matter what I try, the boss works fine for me. Without a log of what's happening I can't find the source of the issue.

Hi, please see - https://github.com/Safrodev/Archon/issues/44
This was crashing our server before but looks like it was fixed in previous versions?   Have you tested different scenarios with Neruina mod installed on a local server?

**Comment by Safrodev** [comment]
This specific crash should be fixed but it is fine now. I changed the projectile the boss fires which should no longer cause the crash. Please let me know if there is still any issues.
