### ISSUE TITLE
channeler destroys blocks

### ISSUE THREAD

**Issue by Helioux** [Safrodev/Archon#5]
after using the channeler to mine, I found that when I used it on diamonds it destroyed the ore and the diamonds that resulted from it.

after using it on a diamond ore, it does the same to every other block you use it on until the server or world is restarted.

additionally the channeler does no work on a few of the blocks listed in NEI (redstone and lapis to name two)

**Comment by Safrodev** [comment]
This is most likely a compat or serverside issue. Are you on the latest version? If you are playing a modpack on curseforge would you mind telling me the name?

**Comment by Helioux** [comment]
here is my mod list:

[✔️] architectury-4.1.32
  [✔️] archon-0.2.2
  [✔️] balm-fabric-3.0.0+0
  [✔️] Botania-1.18.2-431-FABRIC
  [✔️] carryon-1.18.2-1.17.0.8
  [✔️] cc-restitched-1.100.5
  [✔️] chisel-1.4.5+1.18.x
  [✔️] cloth-config-6.2.57-fabric
  [✔️] ColoredLamps-0.1
  [✔️] Controlling-forge-1.18.2-9.0+17
  [✔️] conveyor-belts-1.5
  [✔️] craftingtweaks-fabric-1.18-13.0.0
  [✔️] denseores-1.2.2+1.18.2
  [✔️] fabric-api-0.50.0+1.18.2
  [✔️] fabric-language-kotlin-1.7.1+kotlin.1.6.10
  [✔️] immersive-portals-1.3.3-mc1.18.2-fabric
  [✔️] itemsortermod-fabric-1.18.2-1.10.0
  [✔️] malilib-fabric-1.18.2-0.12.1
  [✔️] megane-7.4.0
  [✔️] mobscarecrow-1.2.2
  [✔️] modmenu-3.0.1
  [✔️] ngv-1.2.0
  [✔️] omnihopper-1.0.0
  [✔️] Patchouli-1.18.2-66-FABRIC
  [✔️] phosphor-fabric-mc1.18.x-0.8.1
  [✔️] Rain-Growth
  [✔️] RebornCore-5.2.0-beta.2
  [✔️] RoughlyEnoughItems-8.1.449
  [✔️] TechReborn-5.2.0-beta.2
  [✔️] tombstone-7.4.2-1.18.2
  [✔️] trinkets-3.3.0
  [✔️] waystones-fabric-1.18.2-10.0.0
  [✔️] wthit-fabric-4.8.1
  [✔️] Xaeros_Minimap_22.5.0_Fabric_1.18.2
  [✔️] XaerosWorldMap_1.20.6_Fabric_1.18.2
  [✔️] youre-in-grave-danger-1.3.1
  
  I could send you my log for the issue, but it doesnt seem to appear there, ive noticed the issue also arises with the channeler when used on sand as well. Ive been trying to pin down the exact conditions and disabling mods one by one, but it seems to persist no matter what I try. it is the latest version.

**Comment by Helioux** [comment]
the problem persists with only your mod and recommended mods+ their requirements: Architectury, Archon, Cloth-configv6, fabric-api 0.50, Patchouli, REI.

steps to replicate:
-install mod-list above on 1.18.2 client
-open a creative survival
-use channeler on something abundant
-vary clicking speed
-9/10 it stops working after about 3-4 uses

**Comment by Safrodev** [comment]
Thank you for the information. I will have to do some testing and will try to pinpoint the problem.

**Comment by Safrodev** [comment]
After running multiple tests on a fresh 1.18.2 client, I have not been able to find any issues with the channeler. It seems to work as an intended and all items drop. 

Possible Problems: 
- You ran out of mana and were unable to channel
- The item flung out or got stuck in a block
- You were on an outdated version (unlikely the cause but still possible)

I forgot to mention before, but lapis has no channeling recipe on purpose, though I'm not sure why redstone doesn't have one for you.

**Comment by Helioux** [comment]
1. its not a mana issue, the staff will continue to not function properly after mana has been allowed to recharge, it persists until relaunching the game.

2. possible they got flung but weve tested it so extensively that wever even tried using it on singular blocks that had no block on any of its adjacent spaces, the problem persists, the ore disappears and drops nothing, the entity count in the chunk doesnt even change.
 
3. right, i did notice i was using a older version but the problem persisted after update.

Id imagine its an incompatibility with some amount of mods we have along side it

**Comment by Safrodev** [comment]
I honestly have no idea what’s going here. It may not even be a compatibility problem but I have no clues as to what’s causing it. Sorry about this.

**Comment by FueledByPants** [comment]
This issue is happening on my server with my friends on Medieval Minecraft 1.18.2 v7. Tested it with sand and got 4 dust, then wouldnt work anymore. Dropped weapon, dropped the dust, brock a sand block then replaced it, then nothing else could fix it. I went to a tree as well and it dropped 16 planks and after channelling 4 blocks it doesn't work anymore for that one either.

**Comment by Safrodev** [comment]
I've just released a new version on curseforge (may be pending) which might fix the bug. Let me know if it does or does not work.

**Comment by Helioux** [comment]
this seems to have fixed the bug, what was the bug if you dont mind me asking?

**Comment by Safrodev** [comment]
The bug was an issue with how the items were spawned when channeling. I’m not sure why it happened, but I just changed it to a safer method.

**Comment by FueledByPants** [comment]
The bug has been fixed on everything for me except for sand now. It may have something to do with the speed at which I right clicked on the sand? other stuff still works but no matter how slow sand doesnt produce dust anymore
