### ISSUE TITLE
Using Cloudshot spell on an entity instantly crashed the game

### ISSUE THREAD

**Issue by Cremeagg** [Safrodev/Archon#50]
Using Cloudshot spell on an entity like a mob or a player instantly crashed the modded server. Owner refused to give crash log to me, but mods that might have caused conflicts are Simply Skills and Trinkets possibly as they both alter certain stats like damage. Cant think of any other things that could have affected it.

Sorry for the mostly unhelpful report, the guy was weird about me submitting the crashlog but I at least wanted this issue to be known.

**Comment by WUFU1211** [comment]
。

**Comment by WUFU1211** [comment]
I can't understand the World because I can't speak English very well, but I really Hope to Get the mod

**Comment by nellia-rae** [comment]
With only Archon and Spell Power Attributes installed I'm having crashes with both hellbeam and cloudshot. only other spell ive tested is fireball, which works.

Crash logs for the two spells:
[crash-2024-07-05_00.09.02-server.txt](https://github.com/user-attachments/files/16105584/crash-2024-07-05_00.09.02-server.txt)
[crash-2024-07-05_00.10.27-server.txt](https://github.com/user-attachments/files/16105586/crash-2024-07-05_00.10.27-server.txt)

**Comment by nellia-rae** [comment]
Spell Power Attributes version 0.9.19 works, version 0.10 does not.

**Comment by Safrodev** [comment]
The issue occurs because Spell Power renamed some classes/files in newer versions. You will have to use an older version of SP for now, but I’m currently working on an update that will be compatible with the latest version.
