### ISSUE TITLE
Problems with the Inferno coat 

### ISSUE THREAD

**Issue by Pacoconut** [Safrodev/Archon#52]
When I use the skill in Inferno coat in prominence 2, it keeps crashing... Wonder if how to fix it

**Comment by Safrodev** [comment]
Prominence 2 is on an outdated version of Archon. Please update to the latest version.

**Comment by Pacoconut** [comment]
Ummm... we are doing this in aternos server, i wonder if we can update only the archon inside?

**Comment by Safrodev** [comment]
You can by going into the mods folder and replacing the jar file.

**Comment by Pacoconut** [comment]
you mean the mods folder in aternos? or the local curseforge folder

**Comment by Safrodev** [comment]
You need to do it for **both** of them.
