### ISSUE TITLE
Bug when summoning null boss

### ISSUE THREAD

**Issue by marcus-plus** [Safrodev/Archon#53]
Hello! I play on a server with a bunch of friends and I just summoned null for the first time, and was almost immediately kicked from the server with this error code: Internal Exception: net.minecraft.class_148: Exception while adding particle, and now i cant log back onto the server. I've turned off all other clientside mods that would interact with particles in any way and it still instantly kicks me, doesnt even let me load in. There is no way to fix it because firstly I don't know the coordinates of my player location so we cant instant kill the boss, and secondly it doesn't even let me load in so we wouldnt be able to teleport away. I have virtually zero experience with modding and error codes so I can't do much more than I already have. Hope someone can help!

**Comment by Safrodev** [comment]
Fixed in 0.7.32.
