### ISSUE TITLE
archon tar boss isn't spawning.

### ISSUE THREAD

**Issue by ImEden6** [Safrodev/Archon#54]
Currently playing prominence 2, latest update, but tar doesn't spawn with new update? Haven't tried with other bosses.

**Comment by JoseNeto5689** [comment]
Last time I looked, the grimoire text was wrong, it was an emerald and 2 earth essence.

**Comment by Safrodev** [comment]
Yes it is a mistake in the grimoire sorry. It should be two essences instead of two emeralds, I completely forgot to fix it.
