### ISSUE TITLE
Balancing required for some spells.

### ISSUE THREAD

**Issue by JoseNeto5689** [Safrodev/Archon#55]
The damage is a bit abusive, the hellbeam spell for example, with just a little fire damage generated by the prominence ii skill tree, is capable of destroying bosses with extreme ease at the beginning of the game.

**Comment by Safrodev** [comment]
Archon just started using Spell Power so I was waiting for some initial feedback. Currently the spell damage is directly calculated from your element spell power. I can add a config option next update to add a multiplier to the damage (ex. 0.5 will half all spell damage) or change the scaling to be more logarithmic.
