### ISSUE TITLE
README.md for better feedback.

### ISSUE THREAD

**Issue by JoseNeto5689** [Safrodev/Archon#56]
Creating a readme.md would help us generate better feedback, I'm trying to make some small changes to the mod to adapt it to a modpack I'm playing, but due to being a beginner in the area, I'm having a little difficulty generating one. jar, so I believe that a readme.md would add a lot to the project.

**Comment by Safrodev** [comment]
Generating a jar is not specific to Archon, you can look up tutorials or videos online to help with that. You can also just clone the repo to make changes and then generate a jar.
