### ISSUE TITLE
Bug showing corrent max capacity for Super experience pouch

### ISSUE THREAD

**Issue by Danielgubas** [Safrodev/Archon#58]
I am currently playing Prominence 2 modpack on dedicated server, I changed config for "superExperiencePouchMax" which is correctly adjusting max capacity for that pouch but it doesn't show it (meaning currently I have 4000/2920 experience stored)

**Comment by Safrodev** [comment]
Will be fixed in the next update thanks for reporting.

**Comment by Safrodev** [comment]
Fixed as of v0.8.0
