### ISSUE TITLE
Formatting error on newer builds of Fabric

### ISSUE THREAD

**Issue by Sunconure11** [Safrodev/Archon#7]
https://pastebin.com/QRw7G4PZ

**Comment by Safrodev** [comment]
Hm, this may be a mod compat issue. I believe a mod with Fabric ASM is messing with the structure pools. I’ll have to look into it.

**Comment by Sunconure11** [comment]
I think something got fucked on Fabric 0.14.3.

**Comment by Safrodev** [comment]
Fixed in Fabric Loader 0.14.4
